### ISSUE TITLE
Class 'Media' not found in line 142 of shells/media.php

### ISSUE THREAD

**Issue by rvega** [mariuswilms/media#33] opened 2010-08-10 02:20 UTC
I'm using a fresh cake 1.3.3 install and beta 1.3 of the media plugin:

Fatal error: Class 'Media' not found in /Users/rafaelvega/Projects/Active/Library/repo/php/media/plugins/media/vendors/shells/media.php on line 142

If it matters: MacOS 10.6.4, Apache 2.2.15, PHP 5.2.13

I added App::import('Lib', 'Media.Media'); to the beggining of the file and it seems to fix it.

**Comment by mariuswilms** [comment] 2010-08-10 14:49
Thanks for your report. Please checkout the most recent version of the plugin and use the "1.3" branch. This bug has already been fixed.

**Comment by THF-zz** [comment] 2011-03-07 14:47
I had the same problem, and I believe I have the most recent version.

**Comment by mariuswilms** [comment] 2011-03-20 12:21
None of the Media_\* classes is actually being used in the shell. I don't see where such an error could originate from and also I can't reproduce the error myself. Please provide a dump with the error messages and stack trace.

**Comment by pkirk** [comment] 2011-03-31 15:32
Same problem here, resolved using the "git clone" instead of the 1.3.0beta downloaded version.

Thanks.

**Comment by mariuswilms** [comment] 2011-05-04 08:37
This problem has been fixed in a recent version. Please pull from the `next` branch.

**Closed as completed by mariuswilms** 2011-05-04 08:37 UTC
Labels: bug, needmoreinfo
